#!/bin/sh

dir=$(du ~/Pictures/wallpapers | awk '{print $NF}' | dmenu -l 20 -p "choose wallpaper dir")
[ -z $dir ] && exit
chosen=$( sxiv -qrto $dir)
[ -z $chosen ] && exit
feh --bg-scale "$chosen" & notify-send -i "$chosen" "Wallpaper changed to '$chosen'"
