#!/bin/sh

chosen=$( du -a $HOME/Pictures/wallpapers/ | sed 's/.*\s//; /\/$d/d' | dmenu -i -l 20 -p 'Change wallpaper:' )
[ -z "$chosen" ] && exit
feh --bg-center "$chosen" & notify-send "Wallpaper changed to '$chosen'"
