#!/bin/sh

case $(printf "Shut down\nRestart\nLog out\nHibernate" | dmenu -i -p "[ System ]") in
  "Shut down") exec shutdown -h now;;
  "Restart") exec reboot;;
  "Hibernate") exec systemctl hibernate;;
  "Log out") exec echo "awesome.quit()" | awesome-client
esac
