#!/bin/sh

np() { 
	mpc -f '%artist% - %title% \[%time%\]' | sed '/^volume/d; /^\[/d'  | xargs -I @@ notify-send -i ~/Templates/icons/musical.png "Playing:@@" "$(mpc -f '%file%' | sed '/^volume/d; /^\[/d' )" 
}
case "$1" in
	prev) mpc prev & np;;
	next) mpc next & np;;
	info) np;;
	toggle) mpc toggle && notify-send -i ~/Templates/icons/musical.png "mpd $(mpc | sed '/^v/d; s/^\[//; s/\].*//; /\s/d')" ;;
	*) exit ;;
esac
