#!/bin/sh

chosen=$( du -a $HOME/.scripts/ | sed 's/.*\s//; /\.git/d; /\/$/d' | dmenu -i -l 20 -p 'Edit script:')
[ -z "$chosen" ] && exit
$TERMINAL -e $EDITOR $chosen & notify-send "Editing '$chosen'"
